spring:
  application:
    name: nacos-provider
  main:
    allow-bean-definition-overriding: true
demo:
  service:
    version: 1.0.0
    group: nacos


dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://127.0.0.1:8848
server:
  port: 8888